#!/usr/bin/env bash                                                                                                                                               
# write a Bash script with the minimum number of commands to automate your fix                                                                                    

sudo service nginx restart