#!/usr/bin/env bash
# Write a Bash script that displays Holberton School 10 times

x=0
while [ $x -lt 10 ]
        do
        echo "Holberton School"
        if [ $x -eq 8 ];
        then
                echo "Hi"
        fi
        x=$(( x = x +1))
        done    